# Generated by Django 3.1.1 on 2020-09-08 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_playstore_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playstore',
            old_name='slug',
            new_name='link',
        ),
    ]
