# Generated by Django 3.1.1 on 2020-09-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200908_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='playstore',
            name='slug',
            field=models.CharField(default='', max_length=521),
            preserve_default=False,
        ),
    ]
