# Generated by Django 3.1.1 on 2020-09-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_playstore_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='playstore',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
